//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneManagement {
    
    
    public partial class Default {
        
        /// <summary>
        /// UcLogoOfBrand control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PhoneManagement.UserControls.Templates.UcLogoOfBrand UcLogoOfBrand;
        
        /// <summary>
        /// UcAdvertisements control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PhoneManagement.UserControls.Templates.UcAdvertisements UcAdvertisements;
        
        /// <summary>
        /// UcProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PhoneManagement.UserControls.Home.UcProducts UcProducts;
        
        /// <summary>
        /// UcNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PhoneManagement.UserControls.Home.UcNews UcNews;
        
        /// <summary>
        /// UcBannerRight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PhoneManagement.UserControls.Home.UcBannerRight UcBannerRight;
    }
}
